# Generated by Django 4.1.7 on 2023-04-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('aboutyou', models.TextField(max_length=500)),
                ('degree', models.TextField(max_length=500)),
                ('school', models.TextField(max_length=500)),
                ('university', models.TextField(max_length=500)),
                ('experience', models.TextField(max_length=500)),
                ('skills', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images')),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
